apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "democluster"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "democluster"
    spec:
      containers:
        - name: "democluster"
          image: "azureregistry123.azurecr.io/democluster"
          ports:
          - containerPort: 80