on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: azureregistry123.azurecr.io
        username: ${{ secrets.acr_azureregistry123_username }}
        password: ${{ secrets.acr_azureregistry123_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t azureregistry123.azurecr.io/democluster:${{ github.sha }}
        docker push azureregistry123.azurecr.io/democluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_democluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep democlusterdb60 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace democlusterdb60`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: democlusterdb60
        container-registry-url: azureregistry123.azurecr.io
        container-registry-username: ${{ secrets.acr_azureregistry123_username }}
        container-registry-password: ${{ secrets.acr_azureregistry123_password }}
        secret-name: democlusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: democlusterdb60
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          azureregistry123.azurecr.io/democluster:${{ github.sha }}
        imagepullsecrets: |
          democlusterdockerauth